    devices:
        leaf01:
            clag_role: "primary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.12"
            loopback: "10.255.255.1/32"
            bgpasn: "65101"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.2/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.2/24"
        leaf02:
            clag_role: "secondary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.11"
            loopback: "10.255.255.2/32"
            bgpasn: "65102"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.3/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.3/24"
        leaf03:
            clag_role: "primary"
            clag_mac: "44:38:39:FF:00:02"
            clag_backupip: "192.168.0.14"
            loopback: "10.255.255.3/32"
            bgpasn: "65103"
            VLANS:
                - vlan: "30"
                  vrrip: "10.0.30.1/24"
                  vrrmac: "00:00:00:00:1a:30"
                  bond: "SERVER03"
                  interface: "swp1"
                  realip: "10.0.30.2/24"
                - vlan: "40"
                  vrrip: "10.0.40.1/24"
                  vrrmac: "00:00:00:00:1a:40"
                  bond: "SERVER04"
                  interface: "swp2"
                  realip: "10.0.40.2/24"
        leaf04:
            clag_role: "secondary"
            clag_mac: "44:38:39:FF:00:02"
            clag_backupip: "192.168.0.13"
            loopback: "10.255.255.4/32"
            bgpasn: "65104"
            VLANS:
                - vlan: "30"
                  vrrip: "10.0.30.1/24"
                  vrrmac: "00:00:00:00:1a:30"
                  bond: "SERVER03"
                  interface: "swp1"
                  realip: "10.0.30.3/24"
                - vlan: "40"
                  vrrip: "10.0.40.1/24"
                  vrrmac: "00:00:00:00:1a:40"
                  bond: "SERVER04"
                  interface: "swp2"
                  realip: "10.0.40.3/24"
        spine01:
            loopback: "10.255.255.101/32"
            bgpasn: "65201"
        spine02:
            loopback: "10.255.255.102/32"
            bgpasn: "65201"